services:
  - type: web
    env: static
    name: ims-frontend
    rootDir: ims_frontend
    buildCommand: npm ci; npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
